## Exercicios parte 1

In [2]:
import numpy as np

1-a

In [16]:
ar1 = np.ones(8)
ar = np.random.randint(0,10,8)
soma = ar1 + ar
if soma.sum() >= 40:
    matriz = soma.reshape(2,4)
else:
    matriz = soma.reshape(4,2)
print(ar1)
print(ar)
print(soma.sum())
print(matriz)

[1. 1. 1. 1. 1. 1. 1. 1.]
[9 7 3 8 4 6 2 4]
51.0
[[10.  8.  4.  9.]
 [ 5.  7.  3.  5.]]


2

In [40]:
array = np.arange(26)
for i in range(52):
    if i % 2 == 0:
        a = int(i/2)
        array[a] = i

arr  = np.arange(25)
for i in range(51,101):
    if i % 2 == 0:
        a = int((i-50)/2)
        arr[a-1] = i

juncao = np.concatenate((array,arr))
print(array)
print(arr)
print(juncao)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]
[ 52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84  86
  88  90  92  94  96  98 100]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


3

In [54]:
#a
campo = np.zeros((2,2))
#b
linhas = np.random.randint(0,2)
colunas = np.random.randint(0,2)
campo[linhas][colunas] = 1
print(campo)

#c
flag = True

while flag:
    soma = campo.sum()
    if soma != 7:
        linha = int(input("Digite a linha: "))
        coluna = int(input("Digite a coluna: "))
        if campo[linha][coluna] == 2:
            print("Você já escolheu essa posição! Tente novamente!")
        
        elif campo[linha][coluna] == 0:
            campo[linha][coluna] = 2
            print("Nao era bomba!")
        else:
            print("Game Over! :( Try Again!")
            flag = False
    else:
        print("Congratulations! You beat the game! :)")
        flag = False

[[0. 0.]
 [1. 0.]]
Nao era bomba!
Nao era bomba!
Você já escolheu essa posição! Tente novamente!
Nao era bomba!
Congratulations! You beat the game! :)


## Exercicios parte 2

4

In [38]:
linhas = np.random.randint(2,6)
colunas = np.random.randint(2,6)
matriz = np.random.randint(0,10,(linhas,colunas))
print(linhas, colunas)
multiplicacao = linhas * colunas
if multiplicacao % 2 == 0:
    print("A matriz é par")
else:
    print("A matriz é impar")

5 3
A matriz é impar


5

In [50]:
import numpy as np

# Definir seed para reprodutibilidade
np.random.seed(10)

# Criar matriz 4x4 com números aleatórios entre 1 e 50
matriz = np.random.randint(1, 51, (4, 4))
print("Matriz:")
print(matriz)

# a) Calcular a média de cada linha e coluna
medias_linhas = np.mean(matriz, axis=1)
medias_colunas = np.mean(matriz, axis=0)
print("\nMédias das linhas:", medias_linhas)
print("Médias das colunas:", medias_colunas)

# b) Maior valor entre as médias das linhas e colunas
maior_media_linhas = np.max(medias_linhas)
maior_media_colunas = np.max(medias_colunas)
print("\nMaior média das linhas:", maior_media_linhas)
print("Maior média das colunas:", maior_media_colunas)

# c) Contagem de aparições de cada número na matriz
valores, contagens = np.unique(matriz, return_counts=True)
contador = {int(num): int(freq) for num, freq in zip(valores, contagens)}
print("\nFrequência dos números na matriz:", contador)

# Filtrar apenas os números que aparecem exatamente 2 vezes
numeros_duplicados = {num: freq for num, freq in contador.items() if freq == 2}
print("\nNúmeros que aparecem exatamente 2 vezes:", numeros_duplicados)


Matriz:
[[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]

Médias das linhas: [16.   33.75 34.5  23.75]
Médias das colunas: [29.75 24.25 33.75 20.25]

Maior média das linhas: 34.5
Maior média das colunas: 33.75

Frequência dos números na matriz: {1: 2, 9: 1, 10: 2, 16: 1, 26: 1, 29: 1, 30: 2, 37: 1, 41: 1, 43: 1, 49: 1, 50: 2}

Números que aparecem exatamente 2 vezes: {1: 2, 10: 2, 30: 2, 50: 2}
