## Exercicios parte 1

In [2]:
import numpy as np

1-a

In [16]:
ar1 = np.ones(8)
ar = np.random.randint(0,10,8)
soma = ar1 + ar
if soma.sum() >= 40:
    matriz = soma.reshape(2,4)
else:
    matriz = soma.reshape(4,2)
print(ar1)
print(ar)
print(soma.sum())
print(matriz)

[1. 1. 1. 1. 1. 1. 1. 1.]
[9 7 3 8 4 6 2 4]
51.0
[[10.  8.  4.  9.]
 [ 5.  7.  3.  5.]]


2

In [40]:
array = np.arange(26)
for i in range(52):
    if i % 2 == 0:
        a = int(i/2)
        array[a] = i

arr  = np.arange(25)
for i in range(51,101):
    if i % 2 == 0:
        a = int((i-50)/2)
        arr[a-1] = i

juncao = np.concatenate((array,arr))
print(array)
print(arr)
print(juncao)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]
[ 52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84  86
  88  90  92  94  96  98 100]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


3

In [ ]:
#a
campo = np.zeros((2,2))
#b
linhas = np.random.randint(0,2)
colunas = np.random.randint(0,2)
campo[linhas][colunas] = 1
print(campo)

#c -1
flag = True

while flag:
    soma = campo.sum()
    if soma != 7:
        linha = int(input("Digite a linha: "))
        coluna = int(input("Digite a coluna: "))
        if campo[linha][coluna] == 2:
            print("Você já escolheu essa posição! Tente novamente!")
        
        elif campo[linha][coluna] == 0:
            campo[linha][coluna] = 2
            print("Nao era bomba!")
        else:
            print("Game Over! :( Try Again!")
            flag = False
    else:
        print("Congratulations! You beat the game! :)")
        flag = False
#c - 2

[[0. 1.]
 [0. 0.]]
Nao era bomba!
Você já escolheu essa posição! Tente novamente!
Você já escolheu essa posição! Tente novamente!
Nao era bomba!
Você errou! Tente novamente!


## Exercicios parte 2

4

5

In [ ]:
#a

#b

#c

## Exercicios parte 3

1

2

3

4

5